version: '3'

services:
#  app:
#    build:
#      context: .
#    container_name: cloud_saves
#    depends_on:
#      - db
#      - minio
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/coursework
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=Airbender1
#      - SPRING_JPA_GENERATE_DDL=true
#    ports:
#      - '8080:8080'
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio-data:/minio

  db:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Airbender1
      - POSTGRES_DB=coursework

volumes:
  minio-data:
    driver: local

